### ISSUE TITLE
How are multiple entities in a single action handled with retry.actions?

### ISSUE THREAD

**Issue by Mathea90** [amitfin/retry#175]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I want to keep my automations as short as possible so when I need to control multiple similar entities, I would like to do it with a single action which I wrap in "retry.actions":

```
action: retry.actions
data:
  sequence:
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
          - light.arbeitszimmer_led_controller_bucherregal_licht
          - light.schaltaktor_8_fach_az_deckenleuchte
          - light.arbeitszimmer_schreibtischlampe_martin
          - light.arbeitszimmer_schreibtischlampe_renee
  expected_state:
    - "off"
  state_delay: 1
  state_grace: 2
```

I was asking myself if this works with the retry.actions logic. In this example, does every light get its own retry logic or are they somehow handled as a single retry call? In my understanding there could be three scenarios:

1. If e.g. only one light is not successfully switched, retry "understands" this and will perform multiple tries with only this one entity (desired behavior)
2. There will be no retry because at least one light reaches the expected state, which retry.actions determines as a success for the "light.turn_off" action.
3. The whole "light.turn_off" action will be retried with all lights as a block even though only one light is not in its expected state.

Can you tell me which of the three behaviors is currently implemented?
If it's not the first variant, would it be possible to implement this behavior?

### Describe the solution you'd like

I would like to have intelligent retry behavior for each entity id in a single action call.

### Describe alternatives you've considered

The alternative would be to use individual actions for each entity wrapped in individual retry actions, even if their type is the same. This would mean longer automations.

### Additional context

I have an additional question: Most of my dimmable lights have a 1s fade when turning on or off. I assume that the on / off state is updated after the light has reached the final dim value, so after roughly one second. I assume that because of this, I need to use longer "state_delay" and "state_grace" periods (in the range of my provided example). Is my assumption correct or am I exaggerating the retry times?

Thank you for your effort! I am extensively using the retry integration and it made my Home Assistant much more reliable and less prone to manual interventions.
