### ISSUE TITLE
Expose GRACE_PERIOD_FOR_STATE_UPDATE as a service parameter

### ISSUE THREAD

**Issue by rtclauss** [amitfin/retry#26]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to use retry to ensure that lights are turned off when I start to watch a TV series. I use a relatively long transition time of 30 seconds to have a nice dimming effect. However, when `light.turn_off` is called the lights are immediately marked as `off` when actually they are in a transition period to off. Due to some zigbee flakiness in the network, not all the lights will turn all the way off. In the retry code it looks like there is an immediate check if the status of entities is in the matching state. Due to this immediate checking and the `light.turn_off` behavior the lights appear to be off when they're actually not so retry no longer tries again.

### Describe the solution you'd like

I'd like an optional state checking grace period on the `retry.actions` and `retry.call` services. This way I can verify that the lights are well and truly off.

### Describe alternatives you've considered

I could remove the lighting transition but that means I'm losing a nice feature I'd like to have of my automated smart home.

### Additional context

Here's some sample yaml of what I'm trying to do:
```yaml
- service: retry.actions
  data:
    sequence:
      - service: light.turn_off
        target:
          entity_id: 
            - light.basement_group
            - light.living_room
            - light.office
            - light.kitchen
        data:
          transition: 30
    retries: 10
    expected_state:
      - "off"
```
